version: '3.7'
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: rolandsall
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped


  postgres-fraud:
    container_name: postgres-fraud
    image: postgres
    environment:
      POSTGRES_USER: rolandsall
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres-fraud:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - postgres-fraud
    restart: unless-stopped

  pgadmin-fraud:
    container_name: pgadmin-fraud
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin-fraud:/var/lib/pgadmin
    ports:
      - "5051:80"
    networks:
      - postgres-fraud
    restart: unless-stopped

  postgres-notification:
    container_name: postgres-notification
    image: postgres
    environment:
      POSTGRES_USER: rolandsall
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres-notification:/data/postgres
    ports:
      - "5434:5432"
    networks:
      - postgres-notification
    restart: unless-stopped

  pgadmin-notification:
    container_name: pgadmin-notification
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin-notification:/var/lib/pgadmin
    ports:
      - "5052:80"
    networks:
      - postgres-notification
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring

  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - spring

  eureka-service:
    image: rolandsall24/discovery:latest
    container_name: eureka-service
    ports:
      - "8761:8761"
    networks:
      - spring
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin
    healthcheck:
      test: curl --fail -s http://localhost:8761/actuator/health || exit 1
      interval: 1m30s
      timeout: 10s

  gateway-service:
    image: rolandsall24/gateway:latest
    container_name: gateway-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - zipkin
      - eureka-service

  customer-service:
    image: rolandsall24/customer:latest
    container_name: customer-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - eureka-service
      - postgres
      - rabbitmq

  fraud-service:
    image: rolandsall24/fraud:latest
    container_name: fraud-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres-fraud
    depends_on:
      - zipkin
      - eureka-service
      - postgres-fraud
      - rabbitmq

  notification-service:
    image: rolandsall24/notification:latest
    container_name: notification-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres-notification
    depends_on:
      - zipkin
      - eureka-service
      - postgres-notification
      - rabbitmq

networks:
  postgres:
    driver: bridge
  postgres-fraud:
    driver: bridge
  postgres-notification:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  pgadmin-fraud:
  postgres-fraud:
  pgadmin-notification:
  postgres-notification: